### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MCP4725'

### ISSUE THREAD

**Issue by vijaypanchal** [adafruit/Adafruit_Python_MCP4725#3]
Hello,

I am using Adafruit_MCP4725 in Beagle-Bone Black Wireless device.

I am getting error:

> AttributeError: 'module' object has no attribute 'MCP4725'

When I tried to run the example file:
`sudo python simpletest.py`

**Comment by ladyada** [comment]
hiya we've written a new library and guide with easier instructions please visit 
https://learn.adafruit.com/mcp4725-12-bit-dac-tutorial/python-circuitpython
thanks!
